# Generated by Django 3.2 on 2022-06-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='op2c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollmodel',
            name='op3c',
            field=models.IntegerField(default=0),
        ),
    ]
