# Generated by Django 3.2 on 2023-04-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0004_answermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='qid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
